In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_train = pd.read_csv('/kaggle/London/train.csv')
df_test = pd.read_csv('/kaggle/London/test.csv')
df_sub = pd.read_csv('/kaggle/London/sample_submission.csv')

In [4]:
df_train.isna().sum()

ID                         0
fullAddress                0
postcode                   0
country                    0
outcode                    0
latitude                   0
longitude                  0
bathrooms              48479
bedrooms               24843
floorAreaSqM           13806
livingRooms            37040
tenure                  5721
propertyType             508
currentEnergyRating    56814
sale_month                 0
sale_year                  0
price                      0
dtype: int64

In [5]:
df_train = df_train.drop(['ID', 'fullAddress', 'country', 'postcode'], axis = 1)
df_test = df_test.drop(['ID', 'fullAddress', 'country', 'postcode'], axis = 1)

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266325 entries, 0 to 266324
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   outcode              266325 non-null  object
 1   latitude             266325 non-null  float64
 2   longitude            266325 non-null  float64
 3   bathrooms            217846 non-null  float64
 4   bedrooms             241482 non-null  float64
 5   floorAreaSqM         252519 non-null  float64
 6   livingRooms          229285 non-null  float64
 7   tenure               260604 non-null  object
 8   propertyType         265817 non-null  object
 9   currentEnergyRating  209511 non-null  object
 10  sale_month           266325 non-null  int64
 11  sale_year            266325 non-null  int64
 12  price                266325 non-null  int64
dtypes: float64(6), int64(3), object(4)
memory usage: 26.4+ MB

In [7]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16547 entries, 0 to 16546
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   outcode              16547 non-null  object
 1   latitude             16547 non-null  float64
 2   longitude            16547 non-null  float64
 3   bathrooms            13923 non-null  float64
 4   bedrooms             15172 non-null  float64
 5   floorAreaSqM         14541 non-null  float64
 6   livingRooms          14452 non-null  float64
 7   tenure               15957 non-null  object
 8   propertyType         16380 non-null  object
 9   currentEnergyRating  15050 non-null  object
 10  sale_month           16547 non-null  int64
 11  sale_year            16547 non-null  int64
dtypes: float64(6), int64(2), object(4)
memory usage: 1.5+ MB

In [8]:
df_test.isna().sum()

outcode                   0
latitude                  0
longitude                 0
bathrooms              2624
bedrooms               1375
floorAreaSqM           2006
livingRooms            2095
tenure                  590
propertyType            167
currentEnergyRating    1497
sale_month                0
sale_year                 0
dtype: int64

In [9]:
df_train.isna().sum()

outcode                    0
latitude                   0
longitude                  0
bathrooms              48479
bedrooms               24843
floorAreaSqM           13806
livingRooms            37040
tenure                  5721
propertyType             508
currentEnergyRating    56814
sale_month                 0
sale_year                  0
price                      0
dtype: int64

In [10]:
df_train['bathrooms'].value_counts()

bathrooms
1.0    143432
2.0     58789
3.0     11786
4.0      2662
5.0       706
6.0       321
7.0       103
8.0        33
9.0        14
Name: count, dtype: int64

In [11]:
df_test['bathrooms'].value_counts()

bathrooms
1.0    8959
2.0    3944
3.0     761
4.0     170
5.0      57
6.0      23
7.0       5
8.0       3
9.0       1
Name: count, dtype: int64

In [12]:
df_train.loc[df_train['bathrooms'].isna(), 'bathrooms'] = np.random.choice(a = [1.0, 2.0, 3.0, 4.0], size = df_train['bathrooms'].isna().sum(), p = [0.5, 0.3, 0.1, 0.1])
df_test.loc[df_test['bathrooms'].isna(), 'bathrooms'] = np.random.choice(a = [1.0, 2.0, 3.0, 4.0], size = df_test['bathrooms'].isna().sum(), p = [0.5, 0.3, 0.1, 0.1])

In [13]:
df_train['bedrooms'].value_counts()

bedrooms
2.0    90652
3.0    61396
1.0    46794
4.0    27638
5.0    11222
6.0     2940
7.0      595
8.0      185
9.0       60
Name: count, dtype: int64

In [14]:
df_test['bedrooms'].value_counts()

bedrooms
2.0    5562
3.0    3996
1.0    2863
4.0    1803
5.0     686
6.0     194
7.0      50
8.0      13
9.0       5
Name: count, dtype: int64

In [15]:
df_train.loc[df_train['bedrooms'].isna(), 'bedrooms'] = np.random.choice(a = [2.0, 3.0, 1.0, 4.0], size = df_train['bedrooms'].isna().sum(), p = [0.5, 0.3, 0.1, 0.1])
df_test.loc[df_test['bedrooms'].isna(), 'bedrooms'] = np.random.choice(a = [2.0, 3.0, 1.0, 4.0], size = df_test['bedrooms'].isna().sum(), p = [0.5, 0.3, 0.1, 0.1])

In [16]:
df_train['floorAreaSqM'].value_counts()

floorAreaSqM
55.0     4477
70.0     3911
56.0     3761
80.0     3512
54.0     3454
         ...
490.0       2
469.0       1
421.0       1
442.0       1
441.0       1
Name: count, Length: 488, dtype: int64

In [17]:
df_test['floorAreaSqM'].value_counts()

floorAreaSqM
55.0     286
70.0     238
54.0     220
56.0     218
80.0     209
        ...
308.0      1
448.0      1
403.0      1
10.0       1
323.0      1
Name: count, Length: 385, dtype: int64

In [18]:
df_test['floorAreaSqM'].value_counts()

floorAreaSqM
55.0     286
70.0     238
54.0     220
56.0     218
80.0     209
        ...
308.0      1
448.0      1
403.0      1
10.0       1
323.0      1
Name: count, Length: 385, dtype: int64

In [19]:
df_train['floorAreaSqM'].value_counts()

floorAreaSqM
55.0     4477
70.0     3911
56.0     3761
80.0     3512
54.0     3454
         ...
490.0       2
469.0       1
421.0       1
442.0       1
441.0       1
Name: count, Length: 488, dtype: int64

In [20]:
len(df_train['floorAreaSqM'])

266325

In [33]:
df_train['livingRooms'].value_counts()

livingRooms
1.0    211437
2.0     45182
3.0      7891
4.0      1380
5.0       328
6.0        76
7.0        26
8.0         4
9.0         1
Name: count, dtype: int64

In [22]:
len(df_train['livingRooms'])

266325

In [31]:
df_test.isna().sum()

outcode                   0
latitude                  0
longitude                 0
bathrooms                 0
bedrooms                  0
floorAreaSqM              0
livingRooms               0
tenure                  590
propertyType            167
currentEnergyRating    1497
sale_month                0
sale_year                 0
rooms_is_missing          0
area_is_missing           0
dtype: int64

In [46]:
df_train.isna().sum()

outcode                    0
latitude                   0
longitude                  0
bathrooms                  0
bedrooms                   0
floorAreaSqM               0
livingRooms                0
tenure                     0
propertyType             508
currentEnergyRating    56814
sale_month                 0
sale_year                  0
price                      0
rooms_is_missing           0
area_is_missing            0
dtype: int64

In [25]:
df_train['rooms_is_missing'] = df_train['livingRooms'].isna().astype(int)
df_train['area_is_missing'] = df_train['floorAreaSqM'].isna().astype(int)

In [26]:
df_train['livingRooms'] = df_train['livingRooms'].fillna(1.0)

df_train['floorAreaSqM'] = df_train['floorAreaSqM'].fillna(df_train.groupby('livingRooms')['floorAreaSqM'].transform('median'))

In [28]:
df_test['rooms_is_missing'] = df_test['livingRooms'].isna().astype(int)
df_test['area_is_missing'] = df_test['floorAreaSqM'].isna().astype(int)

In [29]:
df_test['livingRooms'] = df_test['livingRooms'].fillna(1.0)

In [30]:
df_test['floorAreaSqM'] = df_test['floorAreaSqM'].fillna(df_test.groupby('livingRooms')['floorAreaSqM'].transform('median'))

In [37]:
print(df_train[df_train['floorAreaSqM'].isna()]['livingRooms'])

Series([], Name: livingRooms, dtype: float64)

In [35]:
df_train['floorAreaSqM'] = df_train['floorAreaSqM'].fillna(df_train['floorAreaSqM'].median())

In [47]:
df_train['propertyType'].value_counts()

propertyType
Purpose Built Flat        68726
Flat/Maisonette           61139
Mid Terrace House         45649
Converted Flat            32552
Semi-Detached House       20475
Terrace Property          15114
End Terrace House         13063
Detached House             6666
Terraced                    927
Bungalow Property           267
Semi-Detached Property      254
Semi-Detached Bungalow      232
Detached Bungalow           186
Detached Property           160
End Terrace Property        149
Mid Terrace Property        120
Mid Terrace Bungalow         67
Terraced Bungalow            38
End Terrace Bungalow         33
Name: count, dtype: int64

In [41]:
len(df_train['tenure'])

266325

In [42]:
df_test['tenure'].value_counts()

tenure
Leasehold    9017
Freehold     6643
Feudal        229
Shared         68
Name: count, dtype: int64

In [44]:
df_train.loc[df_train['tenure'].isna(), 'tenure'] = np.random.choice(a = ['Leasehold', 'Freehold'], size = df_train['tenure'].isna().sum(), p = [0.7, 0.3])
df_test.loc[df_test['tenure'].isna(), 'tenure'] = np.random.choice(a = ['Leasehold', 'Freehold'], size = df_test['tenure'].isna().sum(), p = [0.7, 0.3])

In [45]:
df_train['tenure'].value_counts()

tenure
Leasehold    159943
Freehold     103784
Feudal         1906
Shared          692
Name: count, dtype: int64

In [48]:
df_train['propertyType'] = df_train['propertyType'].fillna('Purpose Built Flat')